// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "@prisma/config";
import { config } from 'dotenv';

// Memuat variabel dari .env.local
config({ path: '.env.local' });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Karena file ini hanya dipakai oleh CLI untuk migrasi/generate,
    // kita cukup memberikan akses langsung (DIRECT_URL) milik Supabase ke sini.
    url: process.env.DIRECT_URL,
  },
});