// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { config } from 'dotenv';

config({ path: '.env.local' })

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // UBAH BARIS INI: Gunakan DIRECT_URL untuk proses db push/migrasi
    url: process.env["DIRECT_URL"], 
  },
});